server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.info.model            # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  messages:
    basename: i18n/Messages,i18n/Pages
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://47.106.122.235/testDb?useUnicode=true&characterEncoding=UTF-8           # 数据库连接地址
    username: admin                                  # 数据库用户名
    password: admin@mysql                            # 数据库连接密码
    filters: stat,wall,log4j
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 2                                   # 数据库连接池的最小维持连接数    
      initial-size: 2                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  rabbitmq:
      host: 47.106.140.110
      port: 5672
      username: admin
      password: admin123
      